// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: grpc/pb/sending/sending.proto

package sending_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SendingGrpcClient is the client API for SendingGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendingGrpcClient interface {
	CreateJobAssignment(ctx context.Context, in *CreateJobAssignmentRequest, opts ...grpc.CallOption) (*CreateJobAssignmentResponse, error)
}

type sendingGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSendingGrpcClient(cc grpc.ClientConnInterface) SendingGrpcClient {
	return &sendingGrpcClient{cc}
}

func (c *sendingGrpcClient) CreateJobAssignment(ctx context.Context, in *CreateJobAssignmentRequest, opts ...grpc.CallOption) (*CreateJobAssignmentResponse, error) {
	out := new(CreateJobAssignmentResponse)
	err := c.cc.Invoke(ctx, "/sending.SendingGrpc/CreateJobAssignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendingGrpcServer is the server API for SendingGrpc service.
// All implementations must embed UnimplementedSendingGrpcServer
// for forward compatibility
type SendingGrpcServer interface {
	CreateJobAssignment(context.Context, *CreateJobAssignmentRequest) (*CreateJobAssignmentResponse, error)
	mustEmbedUnimplementedSendingGrpcServer()
}

// UnimplementedSendingGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedSendingGrpcServer struct {
}

func (UnimplementedSendingGrpcServer) CreateJobAssignment(context.Context, *CreateJobAssignmentRequest) (*CreateJobAssignmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJobAssignment not implemented")
}
func (UnimplementedSendingGrpcServer) mustEmbedUnimplementedSendingGrpcServer() {}

// UnsafeSendingGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendingGrpcServer will
// result in compilation errors.
type UnsafeSendingGrpcServer interface {
	mustEmbedUnimplementedSendingGrpcServer()
}

func RegisterSendingGrpcServer(s grpc.ServiceRegistrar, srv SendingGrpcServer) {
	s.RegisterService(&SendingGrpc_ServiceDesc, srv)
}

func _SendingGrpc_CreateJobAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendingGrpcServer).CreateJobAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sending.SendingGrpc/CreateJobAssignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendingGrpcServer).CreateJobAssignment(ctx, req.(*CreateJobAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SendingGrpc_ServiceDesc is the grpc.ServiceDesc for SendingGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendingGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sending.SendingGrpc",
	HandlerType: (*SendingGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJobAssignment",
			Handler:    _SendingGrpc_CreateJobAssignment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/pb/sending/sending.proto",
}
