// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: grpc/pb/booking/booking.proto

package booking_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookDate    string `protobuf:"bytes,2,opt,name=book_date,json=bookDate,proto3" json:"book_date,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_booking_booking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_booking_booking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_grpc_pb_booking_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetBookDate() string {
	if x != nil {
		return x.BookDate
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetListJobByBookDateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatorId string `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	BookDate  string `protobuf:"bytes,2,opt,name=book_date,json=bookDate,proto3" json:"book_date,omitempty"`
}

func (x *GetListJobByBookDateRequest) Reset() {
	*x = GetListJobByBookDateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_booking_booking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListJobByBookDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListJobByBookDateRequest) ProtoMessage() {}

func (x *GetListJobByBookDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_booking_booking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListJobByBookDateRequest.ProtoReflect.Descriptor instead.
func (*GetListJobByBookDateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_booking_booking_proto_rawDescGZIP(), []int{1}
}

func (x *GetListJobByBookDateRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *GetListJobByBookDateRequest) GetBookDate() string {
	if x != nil {
		return x.BookDate
	}
	return ""
}

type GetListJobByBookDateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobList []*Job `protobuf:"bytes,1,rep,name=job_list,json=jobList,proto3" json:"job_list,omitempty"`
}

func (x *GetListJobByBookDateResponse) Reset() {
	*x = GetListJobByBookDateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_booking_booking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListJobByBookDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListJobByBookDateResponse) ProtoMessage() {}

func (x *GetListJobByBookDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_booking_booking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListJobByBookDateResponse.ProtoReflect.Descriptor instead.
func (*GetListJobByBookDateResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_booking_booking_proto_rawDescGZIP(), []int{2}
}

func (x *GetListJobByBookDateResponse) GetJobList() []*Job {
	if x != nil {
		return x.JobList
	}
	return nil
}

var File_grpc_pb_booking_booking_proto protoreflect.FileDescriptor

var file_grpc_pb_booking_booking_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0x54, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x44, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x59,
	0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x42, 0x79, 0x42, 0x6f,
	0x6f, 0x6b, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x44, 0x61, 0x74, 0x65, 0x22, 0x47, 0x0a, 0x1c, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x42, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6a, 0x6f, 0x62,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x4c, 0x69,
	0x73, 0x74, 0x32, 0x74, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x70,
	0x63, 0x12, 0x65, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x42,
	0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x42, 0x79,
	0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x4a, 0x6f, 0x62, 0x42, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1c, 0x5a, 0x1a, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_pb_booking_booking_proto_rawDescOnce sync.Once
	file_grpc_pb_booking_booking_proto_rawDescData = file_grpc_pb_booking_booking_proto_rawDesc
)

func file_grpc_pb_booking_booking_proto_rawDescGZIP() []byte {
	file_grpc_pb_booking_booking_proto_rawDescOnce.Do(func() {
		file_grpc_pb_booking_booking_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_pb_booking_booking_proto_rawDescData)
	})
	return file_grpc_pb_booking_booking_proto_rawDescData
}

var file_grpc_pb_booking_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_pb_booking_booking_proto_goTypes = []interface{}{
	(*Job)(nil),                          // 0: booking.Job
	(*GetListJobByBookDateRequest)(nil),  // 1: booking.GetListJobByBookDateRequest
	(*GetListJobByBookDateResponse)(nil), // 2: booking.GetListJobByBookDateResponse
}
var file_grpc_pb_booking_booking_proto_depIdxs = []int32{
	0, // 0: booking.GetListJobByBookDateResponse.job_list:type_name -> booking.Job
	1, // 1: booking.BookingGrpc.GetListJobByBookDate:input_type -> booking.GetListJobByBookDateRequest
	2, // 2: booking.BookingGrpc.GetListJobByBookDate:output_type -> booking.GetListJobByBookDateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_pb_booking_booking_proto_init() }
func file_grpc_pb_booking_booking_proto_init() {
	if File_grpc_pb_booking_booking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_pb_booking_booking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pb_booking_booking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListJobByBookDateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pb_booking_booking_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListJobByBookDateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_pb_booking_booking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_pb_booking_booking_proto_goTypes,
		DependencyIndexes: file_grpc_pb_booking_booking_proto_depIdxs,
		MessageInfos:      file_grpc_pb_booking_booking_proto_msgTypes,
	}.Build()
	File_grpc_pb_booking_booking_proto = out.File
	file_grpc_pb_booking_booking_proto_rawDesc = nil
	file_grpc_pb_booking_booking_proto_goTypes = nil
	file_grpc_pb_booking_booking_proto_depIdxs = nil
}
