// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: grpc/pb/booking/booking.proto

package booking_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookingGrpcClient is the client API for BookingGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingGrpcClient interface {
	GetListJobByBookDate(ctx context.Context, in *GetListJobByBookDateRequest, opts ...grpc.CallOption) (*GetListJobByBookDateResponse, error)
}

type bookingGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingGrpcClient(cc grpc.ClientConnInterface) BookingGrpcClient {
	return &bookingGrpcClient{cc}
}

func (c *bookingGrpcClient) GetListJobByBookDate(ctx context.Context, in *GetListJobByBookDateRequest, opts ...grpc.CallOption) (*GetListJobByBookDateResponse, error) {
	out := new(GetListJobByBookDateResponse)
	err := c.cc.Invoke(ctx, "/booking.BookingGrpc/GetListJobByBookDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingGrpcServer is the server API for BookingGrpc service.
// All implementations must embed UnimplementedBookingGrpcServer
// for forward compatibility
type BookingGrpcServer interface {
	GetListJobByBookDate(context.Context, *GetListJobByBookDateRequest) (*GetListJobByBookDateResponse, error)
	mustEmbedUnimplementedBookingGrpcServer()
}

// UnimplementedBookingGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedBookingGrpcServer struct {
}

func (UnimplementedBookingGrpcServer) GetListJobByBookDate(context.Context, *GetListJobByBookDateRequest) (*GetListJobByBookDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListJobByBookDate not implemented")
}
func (UnimplementedBookingGrpcServer) mustEmbedUnimplementedBookingGrpcServer() {}

// UnsafeBookingGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingGrpcServer will
// result in compilation errors.
type UnsafeBookingGrpcServer interface {
	mustEmbedUnimplementedBookingGrpcServer()
}

func RegisterBookingGrpcServer(s grpc.ServiceRegistrar, srv BookingGrpcServer) {
	s.RegisterService(&BookingGrpc_ServiceDesc, srv)
}

func _BookingGrpc_GetListJobByBookDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListJobByBookDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingGrpcServer).GetListJobByBookDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.BookingGrpc/GetListJobByBookDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingGrpcServer).GetListJobByBookDate(ctx, req.(*GetListJobByBookDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingGrpc_ServiceDesc is the grpc.ServiceDesc for BookingGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booking.BookingGrpc",
	HandlerType: (*BookingGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListJobByBookDate",
			Handler:    _BookingGrpc_GetListJobByBookDate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/pb/booking/booking.proto",
}
