// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: grpc/pb/user/user.proto

package user_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllUserIdRequest) Reset() {
	*x = GetAllUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_user_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserIdRequest) ProtoMessage() {}

func (x *GetAllUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_user_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetAllUserIdRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_user_user_proto_rawDescGZIP(), []int{0}
}

type GetAllUserIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListUserId []string `protobuf:"bytes,1,rep,name=list_user_id,json=listUserId,proto3" json:"list_user_id,omitempty"`
}

func (x *GetAllUserIdResponse) Reset() {
	*x = GetAllUserIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_user_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserIdResponse) ProtoMessage() {}

func (x *GetAllUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_user_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetAllUserIdResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllUserIdResponse) GetListUserId() []string {
	if x != nil {
		return x.ListUserId
	}
	return nil
}

var File_grpc_pb_user_user_proto protoreflect.FileDescriptor

var file_grpc_pb_user_user_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22,
	0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x32, 0x53, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x12, 0x47, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_pb_user_user_proto_rawDescOnce sync.Once
	file_grpc_pb_user_user_proto_rawDescData = file_grpc_pb_user_user_proto_rawDesc
)

func file_grpc_pb_user_user_proto_rawDescGZIP() []byte {
	file_grpc_pb_user_user_proto_rawDescOnce.Do(func() {
		file_grpc_pb_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_pb_user_user_proto_rawDescData)
	})
	return file_grpc_pb_user_user_proto_rawDescData
}

var file_grpc_pb_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_pb_user_user_proto_goTypes = []interface{}{
	(*GetAllUserIdRequest)(nil),  // 0: user.GetAllUserIdRequest
	(*GetAllUserIdResponse)(nil), // 1: user.GetAllUserIdResponse
}
var file_grpc_pb_user_user_proto_depIdxs = []int32{
	0, // 0: user.UserGrpc.GetAllUserId:input_type -> user.GetAllUserIdRequest
	1, // 1: user.UserGrpc.GetAllUserId:output_type -> user.GetAllUserIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_pb_user_user_proto_init() }
func file_grpc_pb_user_user_proto_init() {
	if File_grpc_pb_user_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_pb_user_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pb_user_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllUserIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_pb_user_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_pb_user_user_proto_goTypes,
		DependencyIndexes: file_grpc_pb_user_user_proto_depIdxs,
		MessageInfos:      file_grpc_pb_user_user_proto_msgTypes,
	}.Build()
	File_grpc_pb_user_user_proto = out.File
	file_grpc_pb_user_user_proto_rawDesc = nil
	file_grpc_pb_user_user_proto_goTypes = nil
	file_grpc_pb_user_user_proto_depIdxs = nil
}
